# In this notebook, I am going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, I am going to cover:

* Introductionn to tensors
* Getting information from tensors
* Manipulationg tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try out

## Introduction to Tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

For more on tf.constant vist https://www.tensorflow.org/api_docs/python/tf/constant 

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the dimensions of our vector
vector.ndim

1

In [8]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                       [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Create another matrix
another_matrix = tf.constant([[1., 2.],
                              [3., 4.],
                              [5., 6.]], dtype=tf.float16) # specify the data type with dtype argument
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
# The number of dimensions for a matrix should be always 2
another_matrix.ndim

2

In [12]:
# Creating a Tensor 
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# The number of dimensions of our tensor should be always 3
tensor.ndim

3

What I have learned so far:
1. Tensors are the main building blocks of TensorFlow.
2. A tensor is a generalization of vectors and matrices to potentially higher dimensions.
3. The number of dimensions of a tensor is called its rank.
4. The shape of a tensor is the number of elements in each dimension.
5. The data type of a tensor is the type of data it contains (e.g., float32, int32, etc.)

* scalar: a single number
* vector: a number with direction (e.g., wind speed and direction)  
* matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar and 1-dimenstional tensor is a vector)

### Creating tensors with `tf.Variable`

For more info on tf.Variable visit: https://www.tensorflow.org/api_docs/python/tf/Variable

In [ ]:
# Creating tensors with tf.Variable() as above we have created tensors with tf.constant() which are immutable (cannot be changed) but if we want to create a tensor which can be changed then we can use tf.Variable().

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# Trying to change the first element of our changeable tensor
# changeable_tensor[0] = 7

# We get a ResourceVariable object which is not subscriptable (cannot be indexed) to change the value of a tensor we need to use the assign() method
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Trying to change the unchangeable tensor

`unchangeable_tensor[0] = 7` will give an error because we cannot change the value of a tensor created with tf.constant() as they are immutable (cannot be changed) but tensors created with tf.Variable() are mutable (can be changed).
`unchangeable_tensor.assign(7)` 

#### We get an error because we cannot change the value of a tensor created with tf.constant() as they are immutable (cannot be changed) but tensors created with tf.Variable() are mutable (can be changed).

#### Why would we want to change our tensors? When we writing/coding neural networks we might want some tensors to be change and others to be unchange but the catch is that the decision will be made for us behind the scene. 

🔑 **Note:** Rarely in practice will you need to decide wheter to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you.

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers.
Learn more about random tensors here: https://www.tensorflow.org/api_docs/python/tf/random/uniform


In [21]:
# Create a random tensor with values between 0 and 1 of size (3, 4)
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 4))
random_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [22]:
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3, 4))
random_2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [23]:
# To check if they are the same
random_1 == random_2

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

#### Why is it important to use a random tensor with a seed?
Using a seed ensures reproducibility of results. Without a seed, each time you run the code, you'll get different random numbers, making it difficult to reproduce results or debug issues.

### Shuffle the order of elements in a tensor
For more info on shuffiling: https://www.tensorflow.org/api_docs/python/tf/random/shuffle

In [26]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
not_shuffled.ndim

2

In [28]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [29]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

🛠️ **Exercise**: Read through TensorFlow documentation on Random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

💡**Rule 4** If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [33]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to make tensors with tf.ones() and tf.zeros()
`tf.ones`: https://www.tensorflow.org/api_docs/python/tf/ones

`tf.zeros`; https://www.tensorflow.org/api_docs/python/tf/zeros

In [35]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for  numerical computing)

In [38]:
# You can also turn Numpy arrays and Python lists into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25

X = tf.constant(numpy_A, shape=(2, 3, 4)) # turn our NumPy array into a tensor and reshape it to (2, 3, 4)
y = tf.constant(numpy_A)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [40]:
X, y

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you must be aware of the following attributs: 

* Shape: The length (number of elements) of each dimension of a tensor is called its shape. You can get the shape of a tensor with the `tf.shape` attribute.
* Rank: The number of dimensions a tensor has is called its rank. You can get the rank of a tensor with the `tf.rank()` function.
* Axis or Dimension: A particular dimension of a tensor is called an axis. You can get the number of axes (or dimensions) of a tensor with the `tf.ndim` attribute.
* Size: The total number of items in the tensor is called its size. You can get the size of a tensor with the `tf.size()` function.

In [42]:
# Creating a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [48]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Size of tensor:", tf.size(rank_4_tensor))
print("Elements in the 0 axis:", rank_4_tensor.shape[0])
print("Elements in the last axis:", rank_4_tensor.shape[-1])
print("The total number of elements in the tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Size of tensor: tf.Tensor(120, shape=(), dtype=int32)
Elements in the 0 axis: 2
Elements in the last axis: 5
The total number of elements in the tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [50]:
# Get the first 2 elements of each dimension of our rank 4 tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [55]:
# Get the first element from each dimension from each index except for the last one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [56]:
# Creating a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.zeros(shape=(3, 4))
tf.rank(rank_2_tensor)
rank_2_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [57]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [58]:
# Adding in extra dimensions to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [59]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # add a new axis at the end (same as tf.newaxis)
tf.expand_dims(rank_2_tensor, axis=0) # add a new axis at the beginning

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [60]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[1, 2],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [61]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [62]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [63]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [64]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [ ]:
# We can use the tensorflow built-in functions to perform operations on our tensor
# if you want to have the advantage of using TensorFlow's built-in functions, 
# you can use them instead of the operators. They often have additional features and can be more efficient.
print(tf.multiply(tensor, 10)) # same as tensor * 10
print(tf.add(tensor, 10)) # same as tensor + 10
print(tf.subtract(tensor, 10)) # same as tensor - 10
print(tf.divide(tensor, 10))  # same as tensor / 10 

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.2]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


### **Matrix multiplication**
In machine learning, matrix multiplication is one of the most common operations. It is used in many algorithms, including neural networks. In TensorFlow, you can perform matrix multiplication using the `tf.matmul()` function or the `@` operator.

For more info visit: https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

There are two rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them: 

* The inner dimensions must match.
* The resulting matrix has the shape of the outter dimensions.

In [90]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor) # matrix multiplication between tensor and itself

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [91]:
# Matrix multiplication with Python's operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [92]:
A = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
B = tf.constant([[3, 5], [6, 7], [1, 8]])

tf.matmul(A, B), A @ B

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>)

In [93]:
tensor.shape

TensorShape([2, 2])

In [94]:
# Creating a tensor with shape (3, 2)
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Creating a tensor with shape (3, 2)
Y = tf.constant([[1, 2], [3, 4], [5, 6]])


📖 **Resource:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [95]:
X @ tf.transpose(Y) # matrix multiplication between Y and the transpose of X

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [97]:
tf.matmul(Y, tf.transpose(X)) # same as above

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product. 
The dot product is a fundamental operation in linear algebra and is used in various applications, including machine learning and deep learning. It involves multiplying corresponding elements of two matrices and summing the results to produce a new matrix.

You can perform matrix multiplication using:

- The `@` operator (e.g., `X @ Y`)
- `tf.matmul()` function (e.g., `tf.matmul(X, Y)`)
- `tf.tensordot()` function (e.g., `tf.tensordot(X, Y, axes=1)`)

For more info: https://www.tensorflow.org/api_docs/python/tf/tensordot

In [101]:
# Perform the dot product on X and Y (requires X or Y to to be transposed )
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [102]:
# Perform matrix multiplication between X and Y (requires X or Y to be transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [104]:
# Perform matrix multiplication between X and Y (requires X or Y to be reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [106]:
# Check the values of Y, reshape Y and transpose Y
print("Normal Y:")
print(Y, "\n")
print("Reshaped Y:")
print(tf.reshape(Y, (2, 3)))
print()
print("Transposed Y:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Transposed Y:
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
