# In this notebook, I am going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, I am going to cover:

* Introductionn to tensors
* Getting information from tensors
* Manipulationg tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try out

## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

For more on tf.constant vist https://www.tensorflow.org/api_docs/python/tf/constant 

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimensions of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                       [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[1., 2.],
                              [3., 4.],
                              [5., 6.]], dtype=tf.float16) # specify the data type with dtype argument
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [9]:
# The number of dimensions for a matrix should be always 2
another_matrix.ndim

2

In [10]:
# Creating a Tensor 
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# The number of dimensions of our tensor should be always 3
tensor.ndim

3

What I have learned so far:
1. Tensors are the main building blocks of TensorFlow.
2. A tensor is a generalization of vectors and matrices to potentially higher dimensions.
3. The number of dimensions of a tensor is called its rank.
4. The shape of a tensor is the number of elements in each dimension.
5. The data type of a tensor is the type of data it contains (e.g., float32, int32, etc.)

* scalar: a single number
* vector: a number with direction (e.g., wind speed and direction)  
* matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar and 1-dimenstional tensor is a vector)

### Creating tensors with `tf.Variable`

For more info on tf.Variable visit: https://www.tensorflow.org/api_docs/python/tf/Variable

In [12]:
# Creating tensors with tf.Variable() as above we have created tensors with tf.constant() which are immutable (cannot be changed) but if we want to create a tensor which can be changed then we can use tf.Variable().

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Trying to change the first element of our changeable tensor
# changeable_tensor[0] = 7

# We get a ResourceVariable object which is not subscriptable (cannot be indexed) to change the value of a tensor we need to use the assign() method
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Trying to change the unchangeable tensor

`unchangeable_tensor[0] = 7` will give an error because we cannot change the value of a tensor created with tf.constant() as they are immutable (cannot be changed) but tensors created with tf.Variable() are mutable (can be changed).
`unchangeable_tensor.assign(7)` 

#### We get an error because we cannot change the value of a tensor created with tf.constant() as they are immutable (cannot be changed) but tensors created with tf.Variable() are mutable (can be changed).

#### Why would we want to change our tensors? When we writing/coding neural networks we might want some tensors to be change and others to be unchange but the catch is that the decision will be made for us behind the scene. 

🔑 **Note:** Rarely in practice will you need to decide wheter to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you.

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers.
Learn more about random tensors here: https://www.tensorflow.org/api_docs/python/tf/random/uniform


In [14]:
# Create a random tensor with values between 0 and 1 of size (3, 4)
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 4))
random_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [15]:
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3, 4))
random_2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [16]:
# To check if they are the same
random_1 == random_2

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

#### Why is it important to use a random tensor with a seed?
Using a seed ensures reproducibility of results. Without a seed, each time you run the code, you'll get different random numbers, making it difficult to reproduce results or debug issues.

### Shuffle the order of elements in a tensor
For more info on shuffiling: https://www.tensorflow.org/api_docs/python/tf/random/shuffle

In [17]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
not_shuffled.ndim

2

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [19]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

🛠️ **Exercise**: Read through TensorFlow documentation on Random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

💡**Rule 4** If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [20]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to make tensors with tf.ones() and tf.zeros()
`tf.ones`: https://www.tensorflow.org/api_docs/python/tf/ones

`tf.zeros`; https://www.tensorflow.org/api_docs/python/tf/zeros

In [21]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for  numerical computing)

In [23]:
# You can also turn Numpy arrays and Python lists into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25

X = tf.constant(numpy_A, shape=(2, 3, 4)) # turn our NumPy array into a tensor and reshape it to (2, 3, 4)
y = tf.constant(numpy_A)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
X, y

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you must be aware of the following attributs: 

* Shape: The length (number of elements) of each dimension of a tensor is called its shape. You can get the shape of a tensor with the `tf.shape` attribute.
* Rank: The number of dimensions a tensor has is called its rank. You can get the rank of a tensor with the `tf.rank()` function.
* Axis or Dimension: A particular dimension of a tensor is called an axis. You can get the number of axes (or dimensions) of a tensor with the `tf.ndim` attribute.
* Size: The total number of items in the tensor is called its size. You can get the size of a tensor with the `tf.size()` function.

In [25]:
# Creating a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Size of tensor:", tf.size(rank_4_tensor))
print("Elements in the 0 axis:", rank_4_tensor.shape[0])
print("Elements in the last axis:", rank_4_tensor.shape[-1])
print("The total number of elements in the tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Size of tensor: tf.Tensor(120, shape=(), dtype=int32)
Elements in the 0 axis: 2
Elements in the last axis: 5
The total number of elements in the tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [28]:
# Get the first 2 elements of each dimension of our rank 4 tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# Get the first element from each dimension from each index except for the last one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Creating a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.zeros(shape=(3, 4))
tf.rank(rank_2_tensor)
rank_2_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [31]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [32]:
# Adding in extra dimensions to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [33]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # add a new axis at the end (same as tf.newaxis)
tf.expand_dims(rank_2_tensor, axis=0) # add a new axis at the beginning

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [34]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[1, 2],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [35]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [37]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [38]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [39]:
# We can use the tensorflow built-in functions to perform operations on our tensor
# if you want to have the advantage of using TensorFlow's built-in functions, 
# you can use them instead of the operators. They often have additional features and can be more efficient.
print(tf.multiply(tensor, 10)) # same as tensor * 10
print(tf.add(tensor, 10)) # same as tensor + 10
print(tf.subtract(tensor, 10)) # same as tensor - 10
print(tf.divide(tensor, 10))  # same as tensor / 10 

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.2]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


### **Matrix multiplication**
In machine learning, matrix multiplication is one of the most common operations. It is used in many algorithms, including neural networks. In TensorFlow, you can perform matrix multiplication using the `tf.matmul()` function or the `@` operator.

For more info visit: https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

There are two rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them: 

* The inner dimensions must match.
* The resulting matrix has the shape of the outter dimensions.

In [40]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor) # matrix multiplication between tensor and itself

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [41]:
# Matrix multiplication with Python's operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [42]:
A = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
B = tf.constant([[3, 5], [6, 7], [1, 8]])

tf.matmul(A, B), A @ B

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]], dtype=int32)>)

In [43]:
tensor.shape

TensorShape([2, 2])

In [44]:
# Creating a tensor with shape (3, 2)
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Creating a tensor with shape (3, 2)
Y = tf.constant([[1, 2], [3, 4], [5, 6]])


📖 **Resource:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [45]:
X @ tf.transpose(Y) # matrix multiplication between Y and the transpose of X

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [46]:
tf.matmul(Y, tf.transpose(X)) # same as above

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product. 
The dot product is a fundamental operation in linear algebra and is used in various applications, including machine learning and deep learning. It involves multiplying corresponding elements of two matrices and summing the results to produce a new matrix.

You can perform matrix multiplication using:

- The `@` operator (e.g., `X @ Y`)
- `tf.matmul()` function (e.g., `tf.matmul(X, Y)`)
- `tf.tensordot()` function (e.g., `tf.tensordot(X, Y, axes=1)`)

For more info: https://www.tensorflow.org/api_docs/python/tf/tensordot

In [47]:
# Perform the dot product on X and Y (requires X or Y to to be transposed )
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [48]:
# Perform matrix multiplication between X and Y (requires X or Y to be transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [49]:
# Perform matrix multiplication between X and Y (requires X or Y to be reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [50]:
# Check the values of Y, reshape Y and transpose Y
print("Normal Y:")
print(Y, "\n")
print("Reshaped Y:")
print(tf.reshape(Y, (2, 3)))
print()
print("Transposed Y:")
print(tf.transpose(Y))

print("Normal X:")
print(X)

Normal Y:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Transposed Y:
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
Normal X:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [51]:
### Changing the datatype of a tensor

In [52]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [53]:
C = tf.constant([[1, 2], [3, 4], [5, 6]])
C.dtype

tf.int32

In [54]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B.dtype, B

(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>)

In [55]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E.dtype, E

(tf.float32,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float32)>)

In [56]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16.dtype, E_float16

(tf.float16,
 <tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float16)>)

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [57]:
# Getting the absolute value of a tensor
D = tf.constant([-7, -10])

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation:

* Get the `minimum`, `maximum`, `mean`, `sum`, `variance` and `standard deviation` of our tensor

In [58]:
new_tensor = tf.constant(np.random.randint(0, 100, size=50))
print("Minimum value:", tf.reduce_min(new_tensor).numpy())
print("Maximum value:", tf.reduce_max(new_tensor).numpy())
print("Mean value:", tf.reduce_mean(new_tensor).numpy())
print("Sum value:", tf.reduce_sum(new_tensor).numpy())
# print("Variance value:", tf.math.reduce_variance(new_tensor, axis=0))
# print("Standard deviation value:", tf.math.reduce_std(new_tensor, axis=0))

Minimum value: 1
Maximum value: 94
Mean value: 53
Sum value: 2660


🛠️ **Exercise:** With what we've just learned, find the variance and standard deviation of our `new_tensor` tensor using TensorFlow methods. 

In [62]:
# Finding the variance of out tensor
import tensorflow_probability as tfp
tfp.stats.variance(new_tensor)

# you can also use 
tf.math.reduce_variance(tf.cast(new_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=639.1199951171875>

In [60]:
tf.math.reduce_std(tf.cast(new_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.28082275390625>

## Find the positional minimum and maximum of a tensor

The positional minimum and maximum of a tensor can be found using the `tf.argmin()` and `tf.argmax()` functions, respectively.


In [63]:
# Creating a new tensor for finding pisitional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50], minval=0, maxval=100)
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([66.45621  , 44.100677 , 35.28825  , 46.448254 ,  3.3660412,
       68.46724  , 74.01174  , 87.24445  , 22.632635 , 22.319687 ,
       31.038809 , 72.23358  , 13.318718 , 54.80639  , 57.46088  ,
       89.968346 ,  0.9463668, 52.12307  , 63.45445  , 19.93283  ,
       72.942245 , 54.583454 , 10.756552 , 67.67061  , 66.027626 ,
       33.69504  , 60.141766 , 21.062576 , 85.27372  , 44.062172 ,
       94.85276  , 23.752594 , 81.1793   , 52.63394  , 49.4308   ,
       21.612846 , 84.57197  , 87.18841  , 30.838621 , 68.68038  ,
       23.764038 , 78.17228  , 96.713844 ,  6.8701625, 79.87395  ,
       66.02872  , 58.71513  , 16.461695 , 73.810234 , 32.054043 ],
      dtype=float32)>

In [64]:
# Finding the ppsitional maximum
tf.math.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [66]:
# Index on the largest value position
F[tf.math.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=96.7138442993164>

In [67]:
# Finding the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=96.7138442993164>

In [69]:
# Check for equality
F[tf.math.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [70]:
# Find the positional minimum
tf.math.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [71]:
# Find the minimu using the positional minimum
F[tf.math.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9463667869567871>

In [72]:
### Squeezing a tensor (removing all single dimensions)

In [74]:
# Creating a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [75]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [77]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [78]:
### One hot encoding a tensor (turning categorical data into numbers)

In [79]:
# Creating a list of indices
some_list = [0, 1, 2, 3]  # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [80]:
# Specify your own values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

In [81]:
### Squaring, log, square root

In [82]:
# Creating a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [83]:
# Squaring our tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [84]:
# Square root 
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [85]:
# Finding the log of our tensor
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays. In fact, one of the main reasons to use TensorFlow is to take advantage of its ability to run on GPUs and TPUs which can speed up computations significantly compared to NumPy which runs on the CPU.

In [88]:
# Creating a tensor directly from a NumPy array
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
X = tf.constant(numpy_A, shape=(2, 3, 4)) # turn our NumPy array into a tensor and reshape it to (2, 3, 4)
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [89]:
# Convert our tensor back to a NumPy array
X.numpy()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)

In [94]:
# The default types of each are slightly different
numpy_A.dtype, X.dtype

(dtype('int32'), tf.int32)

In [95]:
### Finding access to GPUs

In [101]:
tf.config.list_physical_devices("CPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [102]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


key **Note**: If you have a GPU and TensorFlow is configured to use it, you should see it listed when you run `tf.config.list_physical_devices("GPU")`. If you don't see any GPUs listed, make sure you have the appropriate drivers and CUDA toolkit installed for your GPU.