
# 🛠 TensorFlow Fundamentals Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2. Find the shape, rank and size of the tensors you created in 1.

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

4. Multiply the two tensors you created in 3 using matrix multiplication.

5. Multiply the two tensors you created in 3 using dot product.

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7. Find the min and max values of the tensor you created in 6 along the first axis.

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10. One-hot encode the tensor you created in 9.

📖 00. TensorFlow Fundamentals Extra-curriculum
Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.

Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).

How would you calculate your grocery bill for the month and for the year using tensors?
Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).

Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?

Watch the video "[What's a tensor?](https://www.youtube.com/watch?v=f5liqUk0ZTw)" - a great visual introduction to many of the concepts we've covered in this notebook.

In [1]:
import tensorflow as tf

print(tf.__version__)

2.19.0


In [2]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant() 

scalar = tf.constant(42) # Scalar has 0 dimensions
vector = tf.constant([1, 2, 3, 4, 5]) # Vector has 1 dimension
matrix = tf.constant([[1, 2], [3, 4]]) # Matrix has 2 dimensions 
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # Tensor has 3 dimensions

print("Scalar:", scalar, "\n")
print("Vector:", vector, "\n")
print("Matrix:", matrix, "\n")
print("Tensor:", tensor, "\n")

scalar.ndim, vector.ndim, matrix.ndim, tensor.ndim


Scalar: tf.Tensor(42, shape=(), dtype=int32) 

Vector: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) 

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32) 



(0, 1, 2, 3)

In [3]:
# Find the shape, rank and size of the tensors you created in 1
print("Scalar shape:", scalar.shape, "Rank:", scalar.ndim, "Size:", tf.size(scalar).numpy(), "\n")
print("Vector shape:", vector.shape, "Rank:", vector.ndim, "Size:", tf.size(vector).numpy(), "\n")
print("Matrix shape:", matrix.shape, "Rank:", matrix.ndim, "Size:", tf.size(matrix).numpy(), "\n")
print("Tensor shape:", tensor.shape, "Rank:", tensor.ndim, "Size:", tf.size(tensor).numpy(), "\n")

Scalar shape: () Rank: 0 Size: 1 

Vector shape: (5,) Rank: 1 Size: 5 

Matrix shape: (2, 2) Rank: 2 Size: 4 

Tensor shape: (2, 2, 2) Rank: 3 Size: 8 



In [4]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
random_tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
random_tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
random_tensor1, random_tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.88985765, 0.8566716 , 0.7928188 , ..., 0.09230053, 0.33963633,
         0.9006028 ],
        [0.99301076, 0.8728728 , 0.204723  , ..., 0.9808395 , 0.99076927,
         0.08474922],
        [0.9018167 , 0.70743823, 0.71662295, ..., 0.2502203 , 0.35543287,
         0.28306305],
        [0.15235603, 0.3137288 , 0.1720705 , ..., 0.5088998 , 0.17804205,
         0.5539812 ],
        [0.8720093 , 0.77607083, 0.66106606, ..., 0.4848981 , 0.50850654,
         0.44100606]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.53000474, 0.79958093, 0.10534394, ..., 0.00656235, 0.32398748,
         0.13561535],
        [0.4918388 , 0.32292128, 0.6421379 , ..., 0.77331436, 0.81531835,
         0.28970754],
        [0.45008135, 0.6802584 , 0.14768064, ..., 0.17094278, 0.4392426 ,
         0.3889855 ],
        [0.26423585, 0.26639128, 0.7553301 , ..., 0.09419072, 0.3730756 ,
         0.24963391],
        [0.24711

In [5]:
# Multiply the two tensors you created in 3 using matrix multiplication
result = tf.matmul(random_tensor1, tf.transpose(random_tensor2))
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.053604, 71.525116, 69.034584, 72.90637 , 68.01778 ],
       [76.529236, 79.48035 , 74.8542  , 82.04393 , 74.55145 ],
       [73.33804 , 75.17488 , 70.3053  , 75.981995, 72.64219 ],
       [74.11572 , 74.846245, 72.74803 , 76.63855 , 69.98557 ],
       [77.402504, 78.68979 , 76.6687  , 78.32623 , 76.02256 ]],
      dtype=float32)>

In [6]:
# Or you can use the @ operator for matrix multiplication
result_alt = random_tensor1 @ tf.transpose(random_tensor2)
result_alt

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.053604, 71.525116, 69.034584, 72.90637 , 68.01778 ],
       [76.529236, 79.48035 , 74.8542  , 82.04393 , 74.55145 ],
       [73.33804 , 75.17488 , 70.3053  , 75.981995, 72.64219 ],
       [74.11572 , 74.846245, 72.74803 , 76.63855 , 69.98557 ],
       [77.402504, 78.68979 , 76.6687  , 78.32623 , 76.02256 ]],
      dtype=float32)>

In [7]:
# Or you can use it like this
result_alt2 = tf.linalg.matmul(random_tensor1, random_tensor2, transpose_b=True)
result_alt2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.053604, 71.525116, 69.034584, 72.90637 , 68.01778 ],
       [76.529236, 79.48035 , 74.8542  , 82.04393 , 74.55145 ],
       [73.33804 , 75.17488 , 70.3053  , 75.981995, 72.64219 ],
       [74.11572 , 74.846245, 72.74803 , 76.63855 , 69.98557 ],
       [77.402504, 78.68979 , 76.6687  , 78.32623 , 76.02256 ]],
      dtype=float32)>

In [8]:
# Multiply the two tensors you created in 3 using dot product
dot_product = tf.reduce_sum(random_tensor1 * random_tensor2, axis=-1)
dot_product

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([73.0536  , 79.48036 , 70.3053  , 76.638535, 76.02256 ],
      dtype=float32)>

In [9]:
# Or you can use tf.tensordot for dot product
dot_product_alt = tf.tensordot(random_tensor1, random_tensor2, axes=[[1], [1]])
dot_product_alt

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.053604, 71.525116, 69.034584, 72.90637 , 68.01778 ],
       [76.529236, 79.48035 , 74.8542  , 82.04393 , 74.55145 ],
       [73.33804 , 75.17488 , 70.3053  , 75.981995, 72.64219 ],
       [74.11572 , 74.846245, 72.74803 , 76.63855 , 69.98557 ],
       [77.402504, 78.68979 , 76.6687  , 78.32623 , 76.02256 ]],
      dtype=float32)>

In [10]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

random_values_tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
random_values_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8950623 , 0.08538401, 0.98673856],
        [0.6847559 , 0.4078468 , 0.97472537],
        [0.58761525, 0.6493479 , 0.35958052],
        ...,
        [0.7785591 , 0.15749633, 0.99738026],
        [0.7657542 , 0.7381984 , 0.8179269 ],
        [0.6576518 , 0.01048601, 0.6943656 ]],

       [[0.32028532, 0.08470428, 0.71699476],
        [0.8760371 , 0.2959448 , 0.32884693],
        [0.15815246, 0.12243307, 0.60157   ],
        ...,
        [0.39862847, 0.7279881 , 0.5018873 ],
        [0.92637503, 0.57368386, 0.01353729],
        [0.923398  , 0.7356938 , 0.03180242]],

       [[0.07164037, 0.0712285 , 0.6115955 ],
        [0.6125065 , 0.45120692, 0.3345114 ],
        [0.03654885, 0.41892397, 0.03543305],
        ...,
        [0.6955817 , 0.4471892 , 0.0851841 ],
        [0.6841351 , 0.44081783, 0.03344023],
        [0.04162729, 0.20174205, 0.24370682]],

       ...,

       [[0.5664815 , 0.69019186, 0.27981985],
        [0.45

In [11]:
#  Find the min and max values of the tensor you created in 6 along the first axis

min_values = tf.reduce_min(random_values_tensor, axis=0)
max_values = tf.reduce_max(random_values_tensor, axis=0)

min_values, max_values

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[7.56812096e-03, 5.25116920e-04, 6.03556633e-04],
        [3.81577015e-03, 4.14001942e-03, 6.27040863e-05],
        [2.36892700e-03, 2.73227692e-04, 8.63480568e-03],
        [3.61597538e-03, 4.69267368e-03, 1.90114975e-03],
        [9.08970833e-04, 2.93064117e-03, 9.12904739e-04],
        [3.70216370e-03, 8.48209858e-03, 8.26358795e-04],
        [4.20212746e-04, 1.52373314e-03, 2.05779076e-03],
        [5.44071198e-03, 3.35216522e-03, 1.29365921e-03],
        [3.02898884e-03, 4.52589989e-03, 2.45749950e-03],
        [3.50975990e-03, 7.54380226e-03, 9.04798508e-05],
        [2.01141834e-03, 9.48309898e-04, 1.77800655e-02],
        [1.35810375e-02, 2.47955322e-04, 7.18414783e-03],
        [7.02345371e-03, 1.68800354e-03, 6.33955002e-04],
        [3.76427174e-03, 9.12046432e-03, 3.92675400e-03],
        [1.25052929e-02, 1.02602243e-02, 1.56760216e-04],
        [2.15816498e-03, 1.50144100e-03, 3.64041328e-03],
        [6.93964958e-

In [12]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
random_tensor_4d = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
squeezed_tensor = tf.squeeze(random_tensor_4d, axis=0)
squeezed_tensor.shape

TensorShape([224, 224, 3])

In [13]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value
tensor_10 = tf.constant([1, 3, 5, 7, 9, 2, 4, 6, 8, 0])
max_index = tf.argmax(tensor_10)
max_index

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [14]:
# One-hot encode the tensor you created in 9
one_hot_encoded = tf.one_hot(tensor_10, depth=10)
one_hot_encoded

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>