<a href="https://colab.research.google.com/github/Glockrover/LearnTensorFlow/blob/main/Exercises/01_NeuralNetwork_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 01. Neural network regression with TensorFlow Exercises

1. Create your own regression dataset (or make the one we created in "Create data to view and fit" bigger) and build fit a model to it.

2. Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

3. Try and improve the results we got on the insurance dataset, some things you might want to try include:
  * Building a larger model (how does one with 4 dense layers go?).
  * Increasing the number of units in each layer.
  * Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
  * What happens if you train for longer (say 300 epochs instead of 200)?
  
4. Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

## 📖 01. Neural network regression with TensorFlow Extra-curriculum

* [MIT introduction deep learning lecture 1](https://www.youtube.com/watch?v=7sB052Pz0sQ&ab_channel=AlexanderAmini) - gives a great overview of what's happening behind all of the code we're running.

* Reading: 1-hour of [Chapter 1 of Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/chap1.html) by Michael Nielson - a great in-depth and hands-on example of the intuition behind neural networks.

* To practice your regression modelling with TensorFlow, I'd also encourage you to look through [Kaggle's datasets](https://www.kaggle.com/data), find a regression dataset which sparks your interest and try to model.

## 1. Creating our own data set

We are going to use a simple yet powerful way of seeing if our deep learing model works.
The equation is simple `f(x) = 2x`.
![Equation](https://substackcdn.com/image/fetch/$s_!IeZt!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc0070a50-7da3-43bb-903c-8249d7d08dcb_1600x608.jpeg)



In [ ]:
# First we going to create the dataset
X = [n for n in range(1000)]
y = [n * 2 for n in range(1000)]

In [ ]:
import tensorflow as tf

X = tf.constant(tf.expand_dims(X, axis=-1))
y = tf.constant(tf.expand_dims(y, axis=-1))

# Creating our model
model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(1),

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.5665 - mae: 1262.5665  
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.6940 - mae: 1266.6940 
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.9030 - mae: 1260.9030 
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1295.8898 - mae: 1295.8898 
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.4312 - mae: 1260.4312 
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280.6976 - mae: 1280.6976 
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.6580 - mae: 1250.6580 
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.9253 - mae: 1244.9253
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1287.0975 - mae: 1287.0975 
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1267.1237 - mae: 1267.1237 
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.0785 - mae: 1274.0785 
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0

In [ ]:
# Predict the number from our model
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model1.predict(input)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[1369.4807]], dtype=float32)

## Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

In [ ]:
# Creating our model
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(1,)),
    tf.keras.layers.Dense(50),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240.7590 - mae: 1240.7590
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.5420 - mae: 1266.5420 
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.9762 - mae: 1274.9762 
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240.8392 - mae: 1240.8392
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.5674 - mae: 1252.5674
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.5938 - mae: 1249.5938
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.5671 - mae: 1252.5671
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.8483 - mae: 1263.8483 
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1256.0941 - mae: 1256.0941
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.1333 - mae: 1255.1333 
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.6255 - mae: 1251.6255
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 

In [ ]:
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model2.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[-235.68175]], dtype=float32)

Try and improve the results we got on the insurance dataset, some things you might want to try include:

Building a larger model (how does one with 4 dense layers go?).
Increasing the number of units in each layer.
Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
What happens if you train for longer (say 300 epochs instead of 200)?

In [ ]:
import pandas as pd

insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/insurance.csv")
insurance.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [ ]:
insurance = pd.get_dummies(insurance)
insurance.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False


In [ ]:
from sklearn.model_selection import train_test_split

X = insurance.drop("charges", axis=1)
y = insurance["charges"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
insurance_model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(11,)),
    tf.keras.layers.Dense(75),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(1)
])

insurance_model1.compile(loss=tf.keras.losses.mae,
                         optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                        metrics=["mae"])

insurance_model1.fit(X_train, y_train, epochs=300)

Epoch 1/300


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8854.5117 - mae: 8854.5117     
Epoch 2/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6804.8853 - mae: 6804.8853 
Epoch 3/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6250.4365 - mae: 6250.4365 
Epoch 4/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5898.1851 - mae: 5898.1851 
Epoch 5/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5337.6919 - mae: 5337.6919 
Epoch 6/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4108.1543 - mae: 4108.1543 
Epoch 7/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3747.3069 - mae: 3747.3069 
Epoch 8/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3785.3459 - mae: 3785.3459 
Epoch 9/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4025.8181 - mae: 4025.8181 
Epoch 10/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3808.8521 - mae: 3808.8521 
Epoch 11/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3646.9214 - mae: 3646.9214 
Epoch 12/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/st

In [ ]:
import numpy as np

y_preds = insurance_model1.predict(X_test)

y_test = np.array(y_test)

y_preds, y_test

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


(array([[10383.495  ],
        [ 9141.993  ],
        [10923.545  ],
        [ 7950.5923 ],
        [ 9304.092  ],
        [ 9506.846  ],
        [ 1143.608  ],
        [ 2803.535  ],
        [34728.652  ],
        [ 3029.9175 ],
        [ 5533.3955 ],
        [ 2959.7456 ],
        [ 1599.7382 ],
        [35598.61   ],
        [11038.495  ],
        [ 7707.109  ],
        [ 1737.0138 ],
        [ 9461.397  ],
        [ 5488.7085 ],
        [10747.59   ],
        [31384.697  ],
        [ 2881.4998 ],
        [ 5830.354  ],
        [ 1870.3439 ],
        [30017.904  ],
        [11049.487  ],
        [ 9078.423  ],
        [ 8042.463  ],
        [11231.791  ],
        [ 1904.1741 ],
        [12358.201  ],
        [29757.674  ],
        [ 1672.8706 ],
        [ 9306.069  ],
        [ 8533.843  ],
        [12586.841  ],
        [ 5893.3906 ],
        [ 5283.029  ],
        [ 5460.832  ],
        [10125.328  ],
        [11629.141  ],
        [37085.18   ],
        [  141.55878],
        [41

## Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

In [ ]:
BostonHouses = tf.keras.datasets.boston_housing


(X_train, y_train), (X_test, y_test) = BostonHouses.load_data()

def buid_model():
  model = tf.keras.Sequential([
      tf.keras.layers.Dense(1)
  ])
  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
                 loss=tf.keras.losses.mae,
                 metrics=["mae"])
  return model


model2 = buid_model()
model2.fit(X_train, y_train, epochs=200)

Epoch 1/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38.3539 - mae: 38.3539  
Epoch 2/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.5248 - mae: 16.5248 
Epoch 3/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.2617 - mae: 11.2617 
Epoch 4/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3494 - mae: 11.3494 
Epoch 5/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5223 - mae: 7.5223   
Epoch 6/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5973 - mae: 6.5973 
Epoch 7/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0592 - mae: 6.0592 
Epoch 8/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9016 - mae: 6.9016 
Epoch 9/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2362 - mae: 7.2362 
Epoch 10/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5506 - mae: 7.5506 
Epoch 11/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6744 - mae: 6.6744 
Epoch 12/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7890 - mae: 5.7890 
Epoch 13/200
1

In [ ]:
# Evaluate
model1.evaluate(X_test, y_test)