<a href="https://colab.research.google.com/github/Glockrover/LearnTensorFlow/blob/main/Exercises/01_NeuralNetwork_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 01. Neural network regression with TensorFlow Exercises

1. Create your own regression dataset (or make the one we created in "Create data to view and fit" bigger) and build fit a model to it.

2. Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

3. Try and improve the results we got on the insurance dataset, some things you might want to try include:
  * Building a larger model (how does one with 4 dense layers go?).
  * Increasing the number of units in each layer.
  * Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
  * What happens if you train for longer (say 300 epochs instead of 200)?
  
4. Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

## 📖 01. Neural network regression with TensorFlow Extra-curriculum

* [MIT introduction deep learning lecture 1](https://www.youtube.com/watch?v=7sB052Pz0sQ&ab_channel=AlexanderAmini) - gives a great overview of what's happening behind all of the code we're running.

* Reading: 1-hour of [Chapter 1 of Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/chap1.html) by Michael Nielson - a great in-depth and hands-on example of the intuition behind neural networks.

* To practice your regression modelling with TensorFlow, I'd also encourage you to look through [Kaggle's datasets](https://www.kaggle.com/data), find a regression dataset which sparks your interest and try to model.

## 1. Creating our own data set

We are going to use a simple yet powerful way of seeing if our deep learing model works.
The equation is simple `f(x) = 2x`.
![Equation](https://substackcdn.com/image/fetch/$s_!IeZt!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc0070a50-7da3-43bb-903c-8249d7d08dcb_1600x608.jpeg)



In [1]:
# First we going to create the dataset
X = [n for n in range(1000)]
y = [n * 2 for n in range(1000)]

In [2]:
import tensorflow as tf

X = tf.constant(tf.expand_dims(X, axis=-1))
y = tf.constant(tf.expand_dims(y, axis=-1))

# Creating our model
model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(1),

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1252.6643 - mae: 1252.6643 
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.2942 - mae: 1243.2942
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.2687 - mae: 1249.2687
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.5759 - mae: 1248.5759
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1293.5952 - mae: 1293.5952 
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.9048 - mae: 1248.9048
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1307.2440 - mae: 1307.2440 
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.0785 - mae: 1266.0785 
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1261.2263 - mae: 1261.2263
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.6178 - mae: 1272.6178 
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.4208 - mae: 1258.4208 
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms

In [3]:
# Predict the number from our model
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model1.predict(input)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[352.8155]], dtype=float32)

## Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

In [4]:
# Creating our model
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(1,)),
    tf.keras.layers.Dense(50),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1227.6320 - mae: 1227.6320 
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.3606 - mae: 1241.3606
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1232.7426 - mae: 1232.7426
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1261.3641 - mae: 1261.3641 
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1283.6566 - mae: 1283.6566 
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.5405 - mae: 1259.5405 
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.4834 - mae: 1258.4834
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.0402 - mae: 1255.0402
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.3074 - mae: 1259.3074 
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1284.7893 - mae: 1284.7893 
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.7201 - mae: 1255.7201
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss

In [5]:
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model2.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[-8.613476]], dtype=float32)

Try and improve the results we got on the insurance dataset, some things you might want to try include:

Building a larger model (how does one with 4 dense layers go?).
Increasing the number of units in each layer.
Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
What happens if you train for longer (say 300 epochs instead of 200)?

In [8]:
import pandas as pd

insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/insurance.csv")
insurance.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [15]:
insurance = pd.get_dummies(insurance)
insurance.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False


In [19]:
from sklearn.model_selection import train_test_split

X = insurance.drop("charges", axis=1)
y = insurance["charges"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [20]:
insurance_model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(11,)),
    tf.keras.layers.Dense(75),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(1)
])

insurance_model1.compile(loss=tf.keras.losses.mae,
                         optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                        metrics=["mae"])

insurance_model1.fit(X_train, y_train, epochs=300)

Epoch 1/300


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8939.4355 - mae: 8939.4355  
Epoch 2/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7015.4521 - mae: 7015.4521
Epoch 3/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6456.4341 - mae: 6456.4341
Epoch 4/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6080.2983 - mae: 6080.2983
Epoch 5/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5503.6523 - mae: 5503.6523
Epoch 6/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4187.2085 - mae: 4187.2085
Epoch 7/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3987.0613 - mae: 3987.0613
Epoch 8/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3868.2495 - mae: 3868.2495
Epoch 9/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3859.9204 - mae: 3859.9204
Epoch 10/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3689.1985 - mae: 3689.1985
Epoch 11/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3612.2749 - mae: 3612.2749
Epoch 12/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36

In [30]:
import numpy as np

y_preds = insurance_model1.predict(X_test)

y_test = np.array(y_test)

y_preds, y_test

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


(array([[ 3463.7617],
        [33301.9   ],
        [ 8637.884 ],
        [10325.554 ],
        [33996.145 ],
        [ 5570.7427],
        [11611.634 ],
        [39264.277 ],
        [ 4538.291 ],
        [ 5424.792 ],
        [30044.918 ],
        [29400.387 ],
        [ 4481.287 ],
        [ 5365.364 ],
        [ 6193.8926],
        [ 4620.965 ],
        [36343.145 ],
        [ 2569.4153],
        [12363.876 ],
        [12852.47  ],
        [38554.125 ],
        [10459.192 ],
        [ 7824.4365],
        [13775.361 ],
        [ 5342.0015],
        [ 2600.8955],
        [ 4365.541 ],
        [ 6495.6123],
        [ 1774.8182],
        [ 9836.408 ],
        [12848.771 ],
        [ 8607.875 ],
        [ 8570.194 ],
        [10457.512 ],
        [ 3995.1726],
        [ 5213.3135],
        [10362.568 ],
        [38932.207 ],
        [ 4706.7153],
        [ 6449.6167],
        [13375.713 ],
        [ 7506.0405],
        [30075.174 ],
        [30795.943 ],
        [ 9833.525 ],
        [3